### ISSUE TITLE
Exception: cuDNN failed with status CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by chrontax** [McCloudS/subgen#236]
I have absolutely no idea how to fix this. It's installed standalone.

Log:
```
$ python launcher.py -d   
Environment variables have been loaded from subgen.env
Launcher CLI: DEBUG set to True
subgen.py exists and UPDATE is set to False, skipping download.
Launching subgen.py
2025-08-28 01:16:44,305 INFO: Subgen v2025.08.6
2025-08-28 01:16:44,305 INFO: Threads: 8, Concurrent transcriptions: 2
2025-08-28 01:16:44,305 INFO: Transcribe device: cuda, Model: large-v3
INFO:     Started server process [1020106]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
2025-08-28 01:16:53,256 INFO: Transcribing file from Bazarr/ASR webhook
2025-08-28 01:16:53,256 DEBUG: Model was purged, need to re-create
2025-08-28 01:16:57,786 INFO: Task Bazarr-asr-LHg9is is being handled by ASR.
2025-08-28 01:16:57,786 DEBUG: Queue status: 0 tasks remaining
2025-08-28 01:16:57,892 INFO: Processing audio with duration 23:42.054
Detected Language: japanese
Transcribe:   0%|                                                                                                                                                                       | 0/1422.05 [00:00<?, ?sec/s]
2025-08-28 01:16:58,557 ERROR: Error processing or transcribing Bazarr file Exception: cuDNN failed with status CUDNN_STATUS_EXECUTION_FAILED
2025-08-28 01:16:58,560 DEBUG: Queue idle; clearing model from memory.
2025-08-28 01:16:58,608 DEBUG: CUDA cache cleared.
INFO:     127.0.0.1:53186 - "POST /asr?task=transcribe&language=ja&output=srt&encode=false HTTP/1.1" 200 OK
```

**Comment by chrontax** [comment]
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.76.05              Driver Version: 580.76.05      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1070        Off |   00000000:01:00.0  On |                  N/A |
|  0%   45C    P8              9W /  166W |      13MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by McCloudS** [comment]
Most whisper related stuff isn't supporting CUDA 13 right now, so you may need to downgrade to something that is known working, such as 12.3.2.

**Comment by McCloudS** [comment]
I'd recommend installing 12.3.2 and going from there.  If you're able, using the Docker image will remove the guessing game.

**Comment by chrontax** [comment]
Alright, I got it to work. I had to downgrade cudnn to 9.10.2 because nvidia decided that pascal is too old to still support.
